### ISSUE TITLE
ACID testing

### ISSUE THREAD

**Issue by rapsad** [Henrar/LambdaStackProject#5]
How to test this issue?

**Comment by jbytecoder** [comment]
Since ACID means Atomicy,Consitnecy,Isolation,Durability, I thin this matters should be tested independetly.

Because we're plannig on using in-memory database (I think all NewSQL databases are in-memory) the test for durrability would be turn the serwer hosting database off and on and see if any data are lost.

All other qualities are much less aplicable because our system gathers data on its own not allowing user to insert their own data. User can only query existsing data. We may test that over time our system maintains lets say Consistnecy by submiting controll query every second and testing that data make sesne

**Comment by jbytecoder** [comment]
This one is called off
